// <auto-generated />
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(SmartChefContext))]
    [Migration("20260426041247_UpdateFavoriteCuisinesToList")]
    partial class UpdateFavoriteCuisinesToList
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Backend.Models.CuisineType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CuisineTypes");
                });

            modelBuilder.Entity("Backend.Models.PantryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PantryItems");
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Nature's Best",
                            Category = "fruits",
                            Price = 2.99m,
                            Thumbnail = "https://dummyimage.com/150x150/1e1e1e/ff5a00.png&text=Bananas",
                            Title = "Organic Bananas"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Dairy Farm",
                            Category = "dairies",
                            Price = 3.49m,
                            Thumbnail = "https://dummyimage.com/150x150/1e1e1e/ff5a00.png&text=Milk",
                            Title = "Whole Milk"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Farm Fresh",
                            Category = "meats",
                            Price = 8.99m,
                            Thumbnail = "https://dummyimage.com/150x150/1e1e1e/ff5a00.png&text=Chicken",
                            Title = "Chicken Breast"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Chef's Choice",
                            Category = "sauces",
                            Price = 1.99m,
                            Thumbnail = "https://dummyimage.com/150x150/1e1e1e/ff5a00.png&text=Tomato+Sauce",
                            Title = "Tomato Sauce"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "SnackTime",
                            Category = "snacks",
                            Price = 4.50m,
                            Thumbnail = "https://dummyimage.com/150x150/1e1e1e/ff5a00.png&text=Chips",
                            Title = "Potato Chips"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Nature's Best",
                            Category = "vegetables",
                            Price = 2.50m,
                            Thumbnail = "https://dummyimage.com/150x150/1e1e1e/ff5a00.png&text=Broccoli",
                            Title = "Fresh Broccoli"
                        });
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DietaryPreferences")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend.Models.CuisineType", b =>
                {
                    b.HasOne("Backend.Models.User", null)
                        .WithMany("FavoriteCuisines")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.PantryItem", b =>
                {
                    b.HasOne("Backend.Models.User", "User")
                        .WithMany("PantryItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.User", b =>
                {
                    b.Navigation("FavoriteCuisines");

                    b.Navigation("PantryItems");
                });
#pragma warning restore 612, 618
        }
    }
}
