-- SQL Seed for Cuisine Types (Global)
DELETE FROM CuisineTypes;

INSERT INTO CuisineTypes (Name, CountryOfOrigin) VALUES
('Italian', 'Italy'),
('Mexican', 'Mexico'),
('Chinese', 'China'),
('Indian', 'India'),
('Japanese', 'Japan'),
('French', 'France'),
('Thai', 'Thailand'),
('Greek', 'Greece'),
('Spanish', 'Spain'),
('Turkish', 'Turkey'),
('Vietnamese', 'Vietnam'),
('Korean', 'South Korea'),
('American', 'USA'),
('Brazilian', 'Brazil'),
('Moroccan', 'Morocco'),
('Lebanese', 'Lebanon'),
('Ethiopian', 'Ethiopia'),
('German', 'Germany'),
('Russian', 'Russia'),
('British', 'United Kingdom'),
('Caribbean', 'Caribbean Islands'),
('Peruvian', 'Peru'),
('Argentinian', 'Argentina'),
('Portuguese', 'Portugal'),
('Philippine', 'Philippines'),
('Malaysian', 'Malaysia'),
('Indonesian', 'Indonesia'),
('Egyptian', 'Egypt'),
('Iranian', 'Iran'),
('Pakistani', 'Pakistan'),
('Bengali', 'Bangladesh/India'),
('Cuban', 'Cuba'),
('Jamaican', 'Jamaica'),
('African', 'Various'),
('Cajun', 'USA'),
('Creole', 'USA'),
('Tex-Mex', 'USA'),
('Nordic', 'Scandinavia'),
('Middle Eastern', 'Various'),
('Mediterranean', 'Various'),
('South American', 'Various'),
('Eastern European', 'Various'),
('Western European', 'Various'),
('Southeast Asian', 'Various'),
('East Asian', 'Various'),
('South Asian', 'Various'),
('Central Asian', 'Various');
